pipelines:
  pull-requests:
    '**':
      - step:
          name: Build and Test
          script:
            - npm install
            - npm test
  branches:
    main:
      - step:
          name: Build, Tag, and Publish
          script:
            - npm install
            - npm run build-and-tag
            - git push origin main --tags
            - npm publish
          artifacts:
            - dist/**